version: '3.8'

services:
  loan-db:
    image: postgres:15-alpine
    container_name: loan-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loandb
      POSTGRES_USER: loanuser
      POSTGRES_PASSWORD: loanpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/init_ledger.sql:/docker-entrypoint-initdb.d/02-init_ledger.sql
      - ./db/init_holiday.sql:/docker-entrypoint-initdb.d/03-init_holiday.sql
      - loan-db-data:/var/lib/postgresql/data

volumes:
  loan-db-data:
